const menu = [
    {
      id: 1,
      title: 'Chocolate',
      category: 'Pancake balls',
      price: "60,000",
      img: './images/item-1.jpeg',
      desc: `9 pancake balls with chocolate. `,
    },
    {
      id: 2,
      title: 'Maltesers',
      category: 'Pancake balls',
      price: "80,000",
      img: './images/item-2.jpeg',
      desc: `9 pancake balls,chocolate,white chocolate and Maltesers. `,
    },
    {
      id: 3,
      title: 'Twix',
      category: 'Pancake balls',
      price: "75,000",
      img: './images/item-3.jpeg',
      desc: `9 pancake balls,chocolate and Twix.`,
    },
    {
      id: 4,
      title: 'Hersheys',
      category: 'Pancake balls',
      price: "80,000",
      img: './images/item-4.jpeg',
      desc: ` 9 pancake balls,chocolate,white chocolate and Hersheys `,
    },
    {
      id: 5,
      title: 'galaxy',
      category: 'Pancake balls',
      price: "80,000",
      img: './images/item-5.jpeg',
      desc: `9 pancake balls,chocolate and Galaxy `,
    },
    {
      id: 6,
      title: 'plain',
      category: 'Freezy',
      price: "35,000",
      img: './images/item-6.jpeg',
      desc: `Vanilla ice cream`,
    },
    {
      id: 7,
      title: 'Daim',
      category: 'Pancake balls',
      price: "80,000",
      img: './images/item-7.jpeg',
      desc: `9 pancake balls with chocolate,white chocolate and Daim`,
    },
    {
      id: 8,
      title: 'Toblerone',
      category: 'Pancake balls',
      price: "80,000",
      img: './images/item-8.jpeg',
      desc: `9 pancake balls,chocolate,white chocolate and Toblerone  `,
    },
    {
      id: 9,
      title: 'KitKat',
      category: 'Pancake balls',
      price: "75,000",
      img: './images/item-9.jpeg',
      desc: `9 pancake ballswith chocolate and Hersheys`,
    },
    {
        id: 10,
        title: 'Lotus',
        category: 'Pancake balls',
        price: "80,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake balls with chocolate, Lotus biscoff spread and Lotus biscuits`,
      },
      {
        id: 11,
        title: 'Brownie',
        category: 'Pancake balls',
        price: "75,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake ball swith chocolate,white chocolate and Brownie`,
      },
      {
        id: 12,
        title: 'Mars',
        category: 'Pancake balls',
        price:"75,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake balls with chocolate and Mars`,
      },
      {
        id: 13,
        title: 'white chocolate',
        category: 'Pancake balls',
        price: "65,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake balls with chocolate and white chocolate`,
      },
      {
        id: 14,
        title: 'Oreo',
        category: 'Pancake balls',
        price: "70,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake balls with chocolate, white chocolate and Oreo`,
      },
      {
        id: 15,
        title: 'Crunch',
        category: 'Pancake balls',
        price: "75,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake balls with chocolate, white chocolate and Crunch`,
      },
      {
        id: 16,
        title: 'Milka',
        category: 'Pancake balls',
        price: "80,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake balls with chocolate, white chocolate and Milka`,
      },
      {
        id: 17,
        title: 'Overdose',
        category: 'Pancake balls',
        price: "100,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake balls with chocolate and  4 flavors from your choice`,
      },
      {
        id: 18,
        title: 'Mix2',
        category: 'Pancake balls',
        price: "85,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake balls with chocolate and 2 flavors from your choice`,
      },
      {
        id: 19,
        title: 'Mix3',
        category: 'Pancake balls',
        price: "90,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake balls with chocolate and 3 flavors from your choice`,
      },
      {
        id: 20,
        title: 'lion',
        category: 'Pancake balls',
        price: "80,000",
        img: './images/item-9.jpeg',
        desc: `9 pancake balls with chocolate, white chocolate and Lion`,
      },
      {
        id: 21,
        title: 'freezy',
        category: 'Freezy',
        price: "55,000",
        img: './images/item-9.jpeg',
        desc: `Vanilla ice cream with chocolate,white chocolate and flavor from your choice`,
      },
  ];
  export default menu;