const menu = [
    {
      id: 1,
      title: 'Oreo',
      category: 'Pancake balls',
      price: 75000,
      img: 'C:\Users\AS\Desktop\Pancake.jpg',
      desc: `9 pancake balls,chocolate,white chocolate and Oreo. `,
    },
    {
      id: 2,
      title: 'Maltesers',
      category: 'Pancake balls',
      price: 13.99,
      img: './images/item-2.jpeg',
      desc: `9 pancake balls,chocolate,white chocolate and Maltesers. `,
    },
    {
      id: 3,
      title: 'Twix',
      category: 'Pancake balls',
      price: 6.99,
      img: './images/item-3.jpeg',
      desc: `9 pancake balls,chocolate and Twix.`,
    },
    {
      id: 4,
      title: 'Hersheys',
      category: 'Pancake balls',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: ` 9 pancake balls,chocolate,white chocolate and Hersheys `,
    },
    {
      id: 5,
      title: 'galaxy',
      category: 'Pancake balls',
      price: 22.99,
      img: './images/item-5.jpeg',
      desc: `9 pancake balls,chocolate and Galaxy `,
    },
    {
      id: 6,
      title: 'Twix',
      category: 'Freezy',
      price: 18.99,
      img: './images/item-6.jpeg',
      desc: `Vanilla ice cream with chocolate,white chocolate and Twix`,
    },
    {
      id: 7,
      title: 'Daim',
      category: 'Pancake balls',
      price: 8.99,
      img: './images/item-7.jpeg',
      desc: `9 pancake balls with chocolate,white chocolate and Daim`,
    },
    {
      id: 8,
      title: 'Toblerone',
      category: 'Pancake balls',
      price: 12.99,
      img: './images/item-8.jpeg',
      desc: `9 pancake balls,chocolate,white chocolate and Toblerone  `,
    },
    {
      id: 9,
      title: 'KitKat',
      category: 'Pancake balls',
      price: 16.99,
      img: './images/item-9.jpeg',
      desc: `9 pancake ballswith chocolate and Hersheys`,
    },
  ];
  export default menu;